### ISSUE TITLE
ExceptionInfo not properly handled by ribol "catch"

### ISSUE THREAD

**Issue by aengelberg** [zcaudate/ribol#3]
Because of the way ribol uses ExceptionInfo objects, other ExceptionInfos are not properly caught when they don't belong to ribol.
```clojure
> (manage (throw (ex-info "an error" {:my :data}))
    (catch Throwable t t))
;; throws: ExceptionInfo an error  clojure.core/ex-info (core.clj:4403)
```
I believe the problem is that when ribol catches an ExceptionInfo, if it doesn't belong to ribol it will rethrow it, which doesn't reach the remaining catch clauses in the try block. Perhaps another `try` block should be wrapped around the first one, where all the `parse-try-forms` clauses can go?

**Comment by zcaudate** [comment]
Oh! Great pick up.

Let me have a look at that.

**Comment by zcaudate** [comment]
yeah, excellent suggestion! I've made the changes... got some problems deploying as I'm on a new computer but will do so asap!

**Comment by aengelberg** [comment]
Thank you for the quick fix. Are you planning to write a new test case for the ClojureScript side?

I'm not familiar with JavaScript exception handling, so I have no idea whether my bug can be reproduced with ribol.cljs as well.

**Comment by zcaudate** [comment]
I've added a js test case and it seems to be doing what it's supposed to do v0.4.1 is pushed on to clojars
